[[redirects]]
  from = "/api/*"
  to = "http://109.73.206.80:3000/api/:splat"
  status = 200
  force = true

[[redirects]]
 from = "/public/img/*"
 to = "http://91.186.198.179:3000/public/img/:splat"
 status = 200
 force = true